---

# Application settings.
python_requirements_file: "{{ src_dir }}/requirements/prod.txt"


# Django settings
django_conf_dir: "{{ src_dir }}/{{ project_name }}"
run_django_makemigrations: true


# Django Environment variables. Used when running Django commands
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  PATH: "{{ venv_dir }}/bin"

# NODEJS settings
# Pin-Priority of NodeSource repository
nodejs_nodesource_pin_priority: 500
nodejs_version: '0.12'


# Secret credentials for Django project
project_credentials: "{{ DJANGO_SECRETS }}"  # In provision_proj webservers var file

