---

- name: "Provision a {{ project_name }} production server with everything on it"
  hosts: comboservers
  remote_user: cianan
  become: yes
  become_method: sudo
  become_user: root
  vars:
    - setup_git_repo: no
  vars_files:
    - group_vars/all.yml
    - group_vars/dbservers.yml
    - "host_vars/{{ ansible_os_family }}.yml"
    - group_vars/webservers.yml
    - group_vars/production.yml

  roles:
    - base_debian
    - base_python3
    - db_postgres
    - rabbitmq
    - venv_gunicorn
    - web_nginx
    - supervisor
    - django  # Requires venv_gunicorn, webnginx, supervisor roles
    - celery
    - project_specific
