---

__mysql_daemon: mysqld
__mysql_packages:
  - mysql
  - mysql-server
  - MySQL-python
  - python-devel
  - mysql-devel

__mysql_slow_query_log_file: /var/log/mysql-slow.log
mysql_config_file: /etc/my.cnf
mysql_socket: /var/lib/mysql/mysql.sock
