---

# Setup vhosts
- name: Create a vhost for the application
  rabbitmq_vhost: name={{ rabbitmq_project_vhost }} state=present

# Note: had dev trouble with connecting to rabbitmq. Had to manually change pw.
- name: Create rabbit application user
  rabbitmq_user: user={{ rabbitmq_project_user }}
                 password={{ rabbitmq_project_password }}
                 vhost={{ rabbitmq_project_vhost }}
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: Ensure that the RabbitMQ service is running
  service: name=rabbitmq-server state=started enabled=yes