---

- name: Add the RabbitMQ public GPG key to the apt repo
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
           state=present

- name: Add RabbitMQ to the sources list
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install RabbitMQ server
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - rabbitmq-server

- name: Enable the RabbitMQ Management Console
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq-server

# Setup vhosts
- name: Create a vhost for the application
  rabbitmq_vhost: name={{ rabbitmq_project_vhost }} state=present

# Set up users
- name: Create default admin user
  rabbitmq_user: user={{ rabbitmq_admin_user }}
                 password={{ rabbitmq_admin_password }}
                 vhost=/
                 tags=administrator
                 state=present

# Note: had dev trouble with connecting to rabbitmq. Had to manually change pw.
- name: Create rabbit application user
  rabbitmq_user: user={{ rabbitmq_project_user }}
                 password={{ rabbitmq_project_password }}
                 vhost={{ rabbitmq_project_vhost }}
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: Ensure the default 'guest' user doesn't exist
  rabbitmq_user: user=guest
                 state=absent

- name: Ensure that the RabbitMQ service is running
  service: name=rabbitmq-server state=started enabled=yes