---

# Apache server settings
apache_user: apache
apache_group: apache
apache_enablerepo: "epel"
apache_log_dir: "/var/log/httpd/"

apache_vhosts_filename: "{{ project_name }}.conf"
apache_access_log_file: "{{ apache_log_dir }}/{{ project_name }}_access.log"
apache_error_log_file: "{{ apache_log_dir }}/{{ project_name }}_error.log"
wsgi_filepath: "{{ src_dir }}/{{ project_name }}/wsgi/{{ wsgi_filename }}"

apache_listen_port: 80
apache_listen_port_ssl: 443


apache_vhosts:
  # Additional properties: 'serveradmin, serveralias, extra_parameters'.
  - {servername: "local.dev", documentroot: "/var/www/html"}

apache_vhosts_ssl: []
  # Additional properties: 'serveradmin, extra_parameters'.
  # - {
  #   servername: "local.dev",
  #   documentroot: "/var/www/html",
  #   certificate_file: "/path/to/certificate.crt",
  #   certificate_key_file: "/path/to/certificate.key",
  #   # Optional.
  #   certificate_chain_file: "/path/to/certificate_chain.crt"
  # }

apache_ssl_protocol: "All -SSLv2 -SSLv3 -TLSV1"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

# Only used on Debian/Ubuntu.
#apache_mods_enabled:
#  - rewrite.load
#  - ssl.load
#  - mod_wsgi.load
#apache_mods_disabled: []
