---

nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ log_dir }}/nginx_error.log"
nginx_static_dir: "{{ static_dir }}"
nginx_media_dir: "{{ media_dir }}"

nginx_server_name: "{{ project_web_address }}"
