---

- name: Create the application log file
  file:
    path: "{{ django_log }}"
    owner: "{{ webserver_user }}"
    group: "{{ proj_group }}"
    mode: u=rw,g=rw,o=
    state: touch
  notify: reload nginx

- name: Add gunicorn user to project group
  user: name={{ gunicorn_user }} group={{ proj_group }} state=present

- include: setup_git_repo.yml
  tags: deploy

- include: setup_frontend.yml
  tags: deploy

- include: setup_django.yml
  tags: deploy

- include: set_file_permissions.yml
  tags: deploy
