---

- name: Install PostgreSQL
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
    - libpq-dev
  when: ansible_os_family == "Debian"
  tags: packages


- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

