---

celery_user: celery
celery_group: celery

celery_appname: "celery_{{ project_name }}"
celery_scripts_dir: "{{ venv_dir }}/scripts"
celery_template_file: celery_start.j2

celery_log_dir: "{{ log_dir }}"
celery_log_file: "{{ celery_log_dir }}/{{ celery_appname }}.log"

celery_num_workers: 2
flower_admin_password: password
